// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PDsZa5A7wwm-0VgtQSO93DObVPZAU78',
    appId: '1:701891817101:web:e9afb8e30d7fd2d6033cc4',
    messagingSenderId: '701891817101',
    projectId: 'apsosa',
    authDomain: 'apsosa.firebaseapp.com',
    storageBucket: 'apsosa.firebasestorage.app',
    measurementId: 'G-VF1H8NET37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNm4le74UpEmtGmbTb7fC2zvDwBuaID-w',
    appId: '1:701891817101:android:67a29cb941da39be033cc4',
    messagingSenderId: '701891817101',
    projectId: 'apsosa',
    storageBucket: 'apsosa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hPXxHDecAoyHKXh3N5Xr6wI60d9HAes',
    appId: '1:701891817101:ios:91506a433abdd896033cc4',
    messagingSenderId: '701891817101',
    projectId: 'apsosa',
    storageBucket: 'apsosa.firebasestorage.app',
    iosBundleId: 'com.example.armenia',
  );
}
