# Generated by Django 6.0.4 on 2026-08-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_item',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('delivering', 'Доставляется'), ('delivered', 'Доставлено')], db_index=True, default='processing', max_length=20, verbose_name='Статус доставки'),
        ),
    ]
