# Generated by Django 6.0.4 on 2026-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('buyer', 'покупатель'), ('seller', 'продавец')], default='buyer', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
