# Generated by Django 6.0.4 on 2026-07-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('hy', 'Հայերեն')], default='ru', max_length=5, verbose_name='Язык'),
        ),
    ]
