# Generated by Django 6.0.4 on 2026-07-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('hy', 'Հայերեն')], default='en', max_length=5, verbose_name='Язык'),
        ),
    ]
