# Generated by Django 6.0.4 on 2026-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationalarm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта пользователя'),
        ),
        migrations.AddField(
            model_name='notificationalarm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота пользователя'),
        ),
        migrations.AddField(
            model_name='notificationalarm',
            name='radius_km',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Радиус, км'),
        ),
    ]
