# Generated by Django 6.0.4 on 2026-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('admin_news', 'Новость от администрации'), ('new_product', 'Новый товар'), ('order_created', 'Новый заказ'), ('order_reserved', 'Товар зарезервирован'), ('order_cancelled', 'Заказ отменён'), ('low_stock', 'Мало товара'), ('alarm_match', 'Найдено предложение'), ('favorite_store', 'Любимый магазин'), ('review_reminder', 'Напоминание об оценке'), ('new_nearby_product', 'Новое предложение рядом')], max_length=30, verbose_name='Тип'),
        ),
    ]
