# Generated by Django 6.0.4 on 2026-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_facebook_company_instagram'),
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationalarm',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='notification_alarms', to='company.company', verbose_name='Компании'),
        ),
    ]
