# Generated by Django 6.0.4 on 2026-08-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationalarm_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationalarm',
            name='timezone_offset_minutes',
            field=models.SmallIntegerField(default=0, verbose_name='Смещение часового пояса, минут'),
        ),
    ]
