# Generated by Django 6.0.4 on 2026-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationalarm_timezone_offset_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationalarm',
            name='notify_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Активен до'),
        ),
        migrations.AlterField(
            model_name='notificationalarm',
            name='notify_at',
            field=models.DateTimeField(verbose_name='Активен с'),
        ),
    ]
