# Generated by Django 6.0.4 on 2026-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('phone', models.SmallIntegerField(blank=True, null=True, verbose_name='Телефон отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email отправителя')),
                ('timedate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
