# Generated by Django 6.0.4 on 2026-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон отправителя'),
        ),
    ]
