# Generated by Django 6.0.4 on 2026-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компании'),
        ),
    ]
