# Generated by Django 6.0.4 on 2026-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
