# Generated by Django 6.0.4 on 2026-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_close_time_company_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время открытия'),
        ),
    ]
