# Generated by Django 6.0.4 on 2026-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Внутренний рейтинг'),
        ),
        migrations.AddField(
            model_name='company',
            name='complaints_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество жалоб'),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='company',
            name='successful_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='Успешные заказы'),
        ),
    ]
