# Generated by Django 6.0.4 on 2026-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_company_score_company_complaints_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram'),
        ),
    ]
