# Generated by Django 6.0.4 on 2026-07-13 16:23

import django.core.validators
import django.db.models.deletion
import seller_application.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_company_facebook_company_instagram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('hot', 'Home / HOT'), ('deals', 'Deals')], max_length=20, unique=True, verbose_name='Код направления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Направление организации',
                'verbose_name_plural': 'Направления организаций',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Например: cafe, bakery, grocery-store', max_length=100, unique=True, verbose_name='Код')),
                ('name_en', models.CharField(max_length=150, verbose_name='Название на английском')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Название на русском')),
                ('name_hy', models.CharField(blank=True, max_length=150, verbose_name='Название на армянском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('allowed_channels', models.ManyToManyField(blank=True, help_text='Например, кафе может быть доступно для HOT, а производитель — для DEALS.', related_name='business_categories', to='seller_application.companychannel', verbose_name='Доступные направления')),
            ],
            options={
                'verbose_name': 'Категория бизнеса',
                'verbose_name_plural': 'Категории бизнеса',
                'ordering': ('sort_order', 'name_en'),
            },
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='Название организации')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('business_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон организации')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='Email организации')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон контактного лица')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email контактного лица')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='Название банка')),
                ('iban', models.CharField(blank=True, max_length=100, verbose_name='IBAN / банковский счёт')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, verbose_name='Владелец банковского счёта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=seller_application.models.seller_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), seller_application.models.validate_document_size], verbose_name='Логотип организации')),
                ('public_description', models.TextField(blank=True, verbose_name='Описание организации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('changes_requested', 'Требуются исправления'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена пользователем')], db_index=True, default='draft', max_length=30, verbose_name='Статус')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Текущий шаг регистрации')),
                ('admin_comment', models.TextField(blank=True, help_text='Причина отклонения или описание необходимых исправлений.', verbose_name='Комментарий администратора')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на проверку')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_applications', to='seller_application.businesscategory', verbose_name='Категория бизнеса')),
                ('company', models.OneToOneField(blank=True, help_text='Заполняется после одобрения заявки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_seller_application', to='company.company', verbose_name='Созданная компания')),
                ('requested_channels', models.ManyToManyField(related_name='seller_applications', to='seller_application.companychannel', verbose_name='Запрашиваемые направления')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_seller_applications', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка продавца',
                'verbose_name_plural': 'Заявки продавцов',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SellerApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Учредительный документ'), ('tax', 'Налоговый документ'), ('license', 'Лицензия'), ('food_safety', 'Документ пищевой безопасности'), ('certificate', 'Сертификат'), ('identity', 'Документ ответственного лица'), ('bank', 'Банковский документ'), ('other', 'Другой документ')], default='other', max_length=30, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=seller_application.models.seller_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx']), seller_application.models.validate_document_size], verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seller_application.sellerapplication', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_seller_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ заявки продавца',
                'verbose_name_plural': 'Документы заявок продавцов',
                'ordering': ('created',),
            },
        ),
        migrations.AddIndex(
            model_name='sellerapplication',
            index=models.Index(fields=['user', 'status'], name='seller_app_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapplication',
            index=models.Index(fields=['status', 'created'], name='seller_app_status_date_idx'),
        ),
    ]
