# Generated by Django 6.0.4 on 2026-08-17 12:44

import core.storage_backends
import django.core.validators
import seller_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplicationdocument',
            name='file',
            field=models.FileField(storage=core.storage_backends.get_private_storage, upload_to=seller_application.models.seller_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx']), seller_application.models.validate_document_size], verbose_name='Файл'),
        ),
    ]
