# Generated by Django 6.0.4 on 2026-05-08 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('hot', 'горячая'), ('long', 'долгосрочная')], default='hot', max_length=20, verbose_name='Тип продукта'),
        ),
    ]
