# Generated by Django 6.0.4 on 2026-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_discount_products_type'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='products', to='tag.tag', verbose_name='Тег'),
        ),
    ]
