# Generated by Django 6.0.4 on 2026-05-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара'),
        ),
    ]
