# Generated by Django 6.0.4 on 2026-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='can_use_until',
            field=models.DateField(blank=True, null=True, verbose_name='Можно использовать до'),
        ),
        migrations.AddField(
            model_name='products',
            name='delivery_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Доставка в течение дней'),
        ),
        migrations.AddField(
            model_name='products',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка'), ('both', 'Самовывоз и доставка')], default='pickup', max_length=20, verbose_name='Тип получения'),
        ),
        migrations.AddField(
            model_name='products',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='products',
            name='package_quantity',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Количество в упаковке'),
        ),
    ]
