# Generated by Django 6.0.4 on 2026-06-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_can_use_until_products_delivery_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Продвигаемый товар'),
        ),
        migrations.AddField(
            model_name='products',
            name='promotion_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Продвижение до'),
        ),
    ]
