# Generated by Django 6.0.4 on 2026-06-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_is_promoted_products_promotion_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Вес / объём'),
        ),
    ]
