# Generated by Django 6.0.4 on 2026-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество поделившихся'),
        ),
        migrations.AddField(
            model_name='products',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
