# Generated by Django 6.0.4 on 2026-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_shares_count_products_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активен до'),
        ),
        migrations.AddField(
            model_name='products',
            name='inactive_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Остановлен продавцом'), ('pickup_expired', 'Время получения истекло')], default='', max_length=30, verbose_name='Причина неактивности'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен в продаже'),
        ),
    ]
