# Generated by Django 6.0.4 on 2026-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_active_until_products_inactive_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pickup_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Получение с'),
        ),
        migrations.AddField(
            model_name='products',
            name='pickup_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Получение до'),
        ),
    ]
