# Generated by Django 6.0.4 on 2026-08-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_pickup_from_products_pickup_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирован'), ('published', 'Опубликован')], db_index=True, default='published', max_length=20, verbose_name='Статус публикации'),
        ),
        migrations.AddField(
            model_name='products',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Опубликовать в'),
        ),
        migrations.AddField(
            model_name='products',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактически опубликован'),
        ),
        migrations.AlterField(
            model_name='products',
            name='inactive_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Остановлен продавцом'), ('scheduled', 'Ожидает публикации'), ('pickup_expired', 'Время получения истекло')], default='', max_length=30, verbose_name='Причина неактивности'),
        ),
    ]
