# Generated by Django 6.0.4 on 2026-08-21 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_publication_status_products_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delivery_radius_km',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Радиус доставки, км'),
        ),
    ]
