# Generated by Django 6.0.4 on 2026-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_delivery_radius_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='inactive_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Остановлен продавцом'), ('scheduled', 'Ожидает публикации'), ('pickup_expired', 'Время получения истекло'), ('expiration_expired', 'Срок годности истёк')], default='', max_length=30, verbose_name='Причина неактивности'),
        ),
    ]
